[package]
name = "cloneweb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html5ever = "0.25.1"
tokio = { version = "1.17.0", features = ["full"] }
reqwest = "0.11.9"